micronaut:
  application:
    name: java-swing-tutor-service
  server:
    port: ${JAVA_SWING_TUTOR_SERVICE_PORT:8400}
    cors:
      enabled: true
      configurations:
        webapp:
          allowed-origins:
            - ${WEBAPP_ORIGIN:http://localhost:3000}
            - ${WEBSITE_ORIGIN:http://localhost:3010}
          allowed-methods:
            - GET
            - POST
            - PUT
            - DELETE
            - OPTIONS
          allowed-headers:
            - Content-Type
            - Authorization
          allow-credentials: true
  security:
    enabled: true
    authentication: bearer
    intercept-url-map:
      - pattern: /api/auth/**
        access: isAnonymous()
      - pattern: /api/users/register
        access: isAnonymous()
      - pattern: /api/code-checking/**
        access: isAnonymous()
      - pattern: /api/**
        access: isAuthenticated()

datasources:
  default:
    url: ${JAVA_SWING_TUTOR_DATABASE_URL:jdbc:postgresql://localhost:5450/java_swing_tutor}
    username: ${JAVA_SWING_TUTOR_DATABASE_USER:java_swing_tutor}
    password: ${JAVA_SWING_TUTOR_DATABASE_PASSWORD:java_swing_tutor}
    driverClassName: org.postgresql.Driver
    schema-generate: NONE
    dialect: POSTGRES

service:
  urls:
    auth: ${AUTH_SERVICE_BASE_URL:http://localhost:8100}
    user: ${USER_SERVICE_BASE_URL:http://localhost:8095}

logging:
  level:
    root: ${LOG_LEVEL_ROOT:INFO}
    com.posadskiy.javaswingtutor.service: ${LOG_LEVEL_APP:INFO}
    io.micronaut: ${LOG_LEVEL_MICRONAUT:INFO}

